#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Deerpig: The Runbooks & The Diatribes
#+STARTUP: showall
#+PROPERTY: filename 
#+INCLUDE: ./inc/head.org
#+HTML_HEAD: <link href="./css/index.css" rel="stylesheet" type="text/css" />
  :PROPERTIES:
  :Name: /home/deerpig/proj/deerpig/deerpig-install/index.org
  :Created: 2016-08-20T16:40@Wat Phnom (11.5733N17-104.925295W)
  :ID: 5995dc73-91da-4940-bae1-efb75ce040d4
  :URL:
  :END:
#+INCLUDE: ./inc/macros.org
#+INCLUDE: ./inc/links.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* About these pages

#+begin_quote
This page describes the various installation guides & documentation
that I use personally and professionally.  Please be aware that I am a
old-school Emacs user and Lisp hacker, and have a somewhat eclectic
tool chain and work flow that revolves around emacs, orgmode, the
bash shell and a browser.  I hope these pages are useful to others,
but I'm not holding my breath.  You can find the source code for the
site on [[gh:deerpig][GitHub]], and remember, forking shall set you free!
#+end_quote

*NOTE*: 2016-8-28 -- This site is quickly diverging from its original
pupose of being a bunch of personal =runbooks= for my work.  I will
break out all non-deerpig material into a new repo and website soon.

* Recent Activity

Recent change activity on http://github.com/deerpig/deerpig-install

#+BEGIN_SRC sh :exports results :results silent
githubchart -u deerpig ./img/contrib.svg
#+END_SRC

#+RESULTS:

[[./img/contrib.svg]]

#+HTML: <div class="contrib-legend text-small text-muted" title="A summary of pull requests, issues opened, and commits to the default and gh-pages branches.">
#+HTML:  <span>Less</span>
#+HTML:   <ul class="legend">
#+HTML:     <li style="background-color: #eee"></li>
#+HTML:     <li style="background-color: #d6e685"></li>
#+HTML:     <li style="background-color: #8cc665"></li>
#+HTML:     <li style="background-color: #44a340"></li>
#+HTML:     <li style="background-color: #1e6823"></li>
#+HTML:   </ul>
#+HTML:  <span>More</span>
#+HTML: </div>

* Feedback

Please make a [[https://github.com/deerpig/deerpig-install][pull request]] on Github to suggest improvements or add
clarifications. Please use the [[http://bugs.chenla.org/support/][chenla issue tracker]] to ask questions.

* Runbooks 
  - [[./bunsen-install.html][Bunsen Labs install]]
  - [[./kinto-vm-install.html][Kinto Cloud new vm install]]
  - [[./jekyll-new-site.html][Creating a new static website]]
  - [[./tracker-install.html][Roundup Issue Tracker install]]
  - Mattermost & IRCD Hybrid Install
  - GitoLite3 & CGit Install
* Emacs & Orgmode Config
  - Dot Emacs
  - Orgmode Configuration
* Handbooks
This section will be split off to become:

#+begin_quote
/The Scopic Library: Handbooks, Specifications, Conventions & Best
Practices/ which will be part of Chenla's /Primer/.
#+end_quote

  - Team
  - Engineering
  - Task & Project Planning
  - Publishing
  - Communications
  - Citations
  - [[./hb-collaboration.org][Collaboration]]
  - [[./hb-conventions.org][Conventions]]
  - Version Control
  - [[./hb-doc-production.org][Documentation Production]]
* Colophon
  - Making this document
  - What is a Deerpig?
* Licence

#+begin_quote
The MIT License (MIT)

Copyright (c) 2016 deerpig

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
#+end_quote
