#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bash Prompt
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/runbooks/rb-fancy-prompts.org
:Created:   2017-09-12T11:46@Prek Leap (11.642600N-104.919210W)
:ID:        a00f1bb2-4b70-48f6-8eda-d1a5ceb7a09f
:VER:       558463684.309171212
:GEO:       48P-491193-1287029-15
:BXID:      proj:EUV4-5438
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Bash prompts are one of those things that might first seem trivial,
but actually make life a lot easier on your work flow.  It's not
uncomon to have 5 or even 10 shell windows open at the same time, many
of which will be ssh'd into different hosts.  It's important that you
can tell at a glance what user you are logged in as, the name of the
host you are logged into and the path and directory name of where you
are presently in.

There are a large number of pages on the web that talk about how to
format prompts, a few of which I link to below.

For my purposes, I have a two link prompt with user@host and path.
I use different colors for host names depending on which host group I
am working in.

If you don't know already, the following should be placed in your
~/.bashrc file.  I put it at the bottom to make sure nothing else
overwrites it.

#+begin_src sh

# Command Prompt ===========================================
#
# Configure Colors:
COLOR_WHITE='\033[1;37m'
COLOR_LIGHTGRAY='033[0;37m'
COLOR_GRAY='\033[1;30m'
COLOR_BLACK='\033[0;30m'
COLOR_RED='\033[0;31m'e
COLOR_LIGHTRED='\033[1;31m'e
COLOR_GREEN='\033[0;32m'
COLOR_LIGHTGREEN='\033[1;32m'
COLOR_BROWN='\033[0;33m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[0;34m'
COLOR_LIGHTBLUE='\033[1;34m'
COLOR_PURPLE='\033[0;35m'
COLOR_PINK='\033[1;35m'
COLOR_CYAN='\033[0;36m'
COLOR_LIGHTCYAN='\033[1;36m'
COLOR_DEFAULT='\033[0m'

# Use a different host color for different server groups:
#
#  - local     lightgreen  (used on my desktop and laptop boxes)
#  - pnca      white
#  - chenla    pink
#  - customers lightcyan

PS1="\[$COLOR_YELLOW\]╭ \[$COLOR_LIGHTBLUE\]\u\[$COLOR_LIGHTGREEN\]@\H:\[$COLOR_YELLOW\]\w\n╰ $ \[\033[0m\]"


#+end_src

* References & Links

 - [[https://wiki.archlinux.org/index.php/Bash/Prompt_customization][Bash/Prompt customization]] | ArchWiki
 - [[https://misc.flogisoft.com/bash/tip_colors_and_formatting][bash:tip_colors_and_formatting]] | FLOZz' MISC
 - [[https://www.linux.com/learn/how-make-fancy-and-useful-bash-prompt-linux][How to Make a Fancy and Useful Bash Prompt in Linux]] | Linux.com
 - [[http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/index.html][Bash Prompt HOWTO]]
 - [[http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html][Bash Prompt Escape Sequences]]
