#   -*- mode: org; fill-column: 60 -*-

#+TITLE: SSH Keys
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-ssh-keys.org
:Created:   2017-09-08T15:53@Prek Leap (11.642600N-104.919210W)
:ID:        7bf4797d-06b4-4a0b-8be9-56e4c32ced21
:VER:       558132891.916941263
:GEO:       48P-491193-1287029-15
:BXID:      proj:LHC7-4013
:Type:      runbook
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


*  SSH Keys (Linux)


** 1. Install Openssh

Check that open ssh is installed.

#+begin_src sh
sudo apt-get install openssh-server openssh-client
#+end_src

** 2. Create SSH key pair

#+begin_src sh
cd ~/
mkdir .ssh
cd ~/.ssh
ssh-keygen -o -b 4096
#+end_src

This will create a 4096-bit RSA (and SHA256) key pair which should be
pretty solid for the forseeable future.

You will be prompted for a location to save the keys, and for an
optional passphrase.  The passphrase is a backup security measure so
that if your private key is stolen, the attacker will need your
passphrase to be able to use the key.

Two files will be generated, =id_rsa= and =id_rsa.pub=.

Now double check that all permissions on the .ssh directory and keys
are correct.

#+begin_src sh
chmod -R go= ~/.ssh
#+end_src



*** Further Reading

The page on [[https://wiki.archlinux.org/index.php/SSH_keys][SSH Keys]] on the Arch Linux Wiki is excellent,
in-depth and fully referenced.

- [[https://wiki.archlinux.org/index.php/SSH_keys][SSH Keys]] | Arch Linux Wiki
- [[https://www.howtoforge.com/linux-basics-how-to-install-ssh-keys-on-the-shell][Linux Basics: How To Create and Install SSH Keys on the Shell]]


** 3. ssh-copy-id

Copy keys to a remote server.

#+begin_src sh
ssh-copy-id -i ~/.ssh/key-name user@host
#+end_src

** 4. SSH Agent

In order to be able to login to the server without using the password
every time, use SSH Agent during that session.

#+begin_src sh
ssh-agent BASH
ssh-add ~/.ssh/<key-file>
#+end_src

** 5. Disable Password Login

Test that you can login without a password, then open:

#+begin_src sh
emacs /etc/ssh/sshd_config
#+end_src

Search for the PasswordAuthorization section. Uncomment and
change =PasswordAuthentication= from yes to no.

#+begin_example
PasswordAuthentication no
#+end_example

