#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Install Ruby & Jekyll
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-ruby-jekyll.org
:Created:   2017-09-07T07:28@Prek Leap (11.642600N-104.919210W)
:ID:        4eb0c094-9967-486d-a885-02977f5f3242
:VER:       558016186.410367477
:GEO:       48P-491193-1287029-15
:BXID:      proj:KEK2-5215
:Type:      runbook
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

The Jekyll site is notoriously misleading about how easy it
is to install Jekyll.  There is a whole world of things they
assume you know about the Ruby ecosystem.  They make it
sound so easy...

* Ruby

Install =ruby-full= which includes =ruby=, =ruby-headers= and
=ruby gems=.

#+begin_src sh
sudo apt-get install ruby ruby-dev make build-essential
#+end_src


* Edit .bashrc

Edit:

#+begin_src sh
emacs ~/.bashrc
#+end_src

Add the following:

#+begin_example sh
# Ruby exports
export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH
#+end_example

* Install Jekyll

#+begin_src sh
gem install jekyll bundler
#+end_src


* RVM: The Ruby Version Manager

I don't know if this is the best way to install rvm, but it
worked for me.

First install keys:

#+begin_src sh
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
#+end_src

Now install the stable version of rvm.  The leading '\'
ensures that the original version of curl is used for the
download, rather than variations of curl that the system
might be running.

#+begin_src sh
\curl -sSL https://get.rvm.io | bash
#+end_src

Either log out and log back in or run the following to load rvm:

#+begin_src sh
source ~/.rvm/scripts/rvm
#+end_src

Install rvm requirements

Run =rvm requirements= which will prompt you for your sudo
password and install everything that needs to be installed.

#+begin_src sh
rvm requirements
#+end_src

Check your version of ruby:

#+begin_src sh
ruby -v
#+end_src

If you have /ruby-2.1.5/, install rvm ruby-2.1.5 and then set
it as the default.

#+begin_src sh
rvm install ruby-2.1.5
rvm use --default use 2.1.5
#+end_src

* Install Jekyll

#+begin_src sh
gem install jekyll
#+end_src

* Pygments

#+begin_src sh
sudo apt-get install python-pygments
#+end_src
