#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bare Bones .emacs
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/runbooks/rb-bare-bones-emacs.org
:Created:   2017-09-12T12:46@Prek Leap (11.642600N-104.919210W)
:ID:        a347abb9-bd8c-4476-ab50-8fb448b71fb3
:VER:       558467254.011495625
:GEO:       48P-491193-1287029-15
:BXID:      proj:QIS8-8806
:Type:      runbook
:Status:    stub
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

My local =.emacs= is /enormous/ and grows by the hour.

But I still finding myself working on other machines, either by
ssh'ing into them or at a different desktop that I use occasionally.

All I need is a very basic dotemacs that I can put on servers when I
set them up to make remote workflow a little easier.

That's all this file is.


* Header

#+begin_src emacs-lisp
  ;;; Deerpig's Barebones .emacs file.
  ;;; (c)2017 Brad Collins, Phnom Penh.
  ;;; MIT Licence
  ;;;
  ;;; This is part of a literate program that was tangled 
  ;;; from either of the following:
  ;;;
  ;;;  https://github.com/deerpig/runbooks/blob/master/rb-bare-bones-emacs.org
  ;;;  http://git.chenla.org/deerpig-public/runbooks/blob/master/rb-bare-bones-emacs.org
  ;;;
  ;;;  Now for a true story:
  ;;;
  ;;;     "Daddy, is there emacs in heaven"
  ;;;
  ;;;     "Well my dear daughter, if there wasn't, you couldn't really
  ;;;     call it heaven, now could you." The father stroked his long
  ;;;     beard thoughtfully and whispered, almost to himself, "But what
  ;;;     keeps me awake at night is if you can take your .emacs with
  ;;;     you!"
  ;;;
  ;;; ===========================================================


#+end_src


* NOX Configuration

** Yes-or-no questions

Don't require typing 'yes" or 'no'

#+begin_src emacs-lisp
;; y-or-n questions -----------------------------------------
(fset 'yes-or-no-p 'y-or-n-p)

#+end_src

** Inhibit startup message

Don't display boilerplate startup message in scratch buffer. This
gives us a nice clean scratch buffer.

#+begin_src emacs-lisp
;; no scratch message ----------------------------------------

(setq initial-scratch-message nil)
#+end_src

** Don't mix tabs and spaces

I know this is a religous issue, but I've found life easier without
tabspace characters mucking things up.

#+begin_src emacs-lisp
;; Don't mix tabs and spaces ---------------------------------
  (setq-default indent-tabs-mode nil) 

#+end_src


* Minimal GUI Configuration 

I know what I'm doing, so don't clutter up the screen with 
the the tool, menu, scroll bars or splash screen.

#+begin_src emacs-lisp
;; No cluttering tool, menu, scroll bars or splash screen.

(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode -1)
(setq inhibit-startup-screen t)
#+end_src

