#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Git Mirror
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-git-mirror.org
:Created: 2017-01-03T13:26@Prek Leap (11.642600N-104.919210W)
:ID: 7e1928e4-a1ea-4f5e-9b69-6f3ae0001f71
:VER:       558129753.295987091
:GEO:       48P-491193-1287029-15
:BXID:      proj:CSL7-8633
:Class:     primer
:Type:      runbook
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

I keep a local mirror of the key repos on my computer on a usb drive.
For the past month or so the ISP at the Phnom Penh office has had
serious routing problems.  For large parts of the day, I can not reach
any hosts on the Ezecom network.  This results in not being able to
sync the computer here with the computer at the office @preakleap.
Since my work is spread between these two offices, this has become a
non trivial problem for me every day.

So I have set up a local mirror of the two repos that always have to
be in sync on a usb drive.  The idea is that I can take the changes
made during the day with me between offices and use the mirror when the
ISP's routing craps out.

* Create empty bare repos on USB drive

#+begin_src sh
mkdir -p /media/deerpig/Transcend/repos/{dot,org}
#+end_src

* Add remotes each repo to be mirrored

#+begin_src sh
cd ~/.dotfiles
git remote add --mirror=push backup /media/deerpig/Transcend/repos/dot
cd ~/org
git remote add --mirror=push backup /media/deerpig/Transcend/repos/org
#+end_src

* First sync

#+begin_src sh
cd ~/.dotfiles
git push backup
cd ~/.org
git push backup
#+end_src

* Create shell script

Create the script file, make it executable and link it to the ~/bin
directory.

#+begin_src sh
touch ~/.dotfiles/mirror.sh
chmod +x ~/.dotfiles/mirror.sh
ln -s ~/.dotfiles/mirror.sh ~/bin/mirror
emacs ~/.dotfiles/mirror.sh
#+end_src

Add the following text and save.

#+begin_src 
*#!/bin/bash
# Mirror directories
DOT=~/.dotfiles
ORG=~/org
# make sure the script is in the path
export PATH=$PATH:/home/deerpig/bin/ ;

# change to build dir and fetch any changes from
# any deployment from other boxes
cd $DOT && \
git push backup && \
    
cd $ORG && \
git push backup && 

exit
#+end_src


