#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Install Bare Metal Server 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-runbook-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Install Bare Metal Server
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/deerpig/runbooks/rb-install-bare-metal.org
  :Created:   2018-07-13T18:59@Prek Leap (11.642600N-104.919210W)
  :ID:        94e0d1cd-6f58-4f1c-a937-4202d9b9919a
  :VER:       584755207.702163602
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:BEV4-0178
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

For now let's assume a generic install of CentOS or Debian, with two
NICs, one pointing to 10.0.0 and the other to 103.56.174.

** Set Hostname

#+begin_src sh
emacs /etc/hostname
#+end_src

Set the hostname:

#+begin_example
<hostname>.kinto.dom
#+end_example

** Turn off SELinux

#+begin_src sh
emacs /etc/selinux/config
#+end_src

Change to disabled.

#+begin_example
SELINUX=disabled
#+end_example

** Turn off Network Manager

On CentOS running systemd:

#+begin_src sh
systemctl disable NetworkManager.service
#+end_src

** Configure Network Interfaces

#+begin_src sh
emacs /etc/sysconfig/network-scripts/
#+end_src

Will open emacs in the network scripts dir.  The interfaces should be
either eth0 and eth1, or they might be using the newfangled naming
system with something like p4p1 and p4p2.

Don't erase the UUID.

Lookup the available interfaces:

#+begin_src sh
ifconfig -a
#+end_src

And note down the MAC addresses for each interface.

Then config each interface:

#+begin_src sh
emacs /etc/sysconfig/network-scripts/ifcg-p4p1
#+end_src

This is connected to a local network that contains servers that are
not directly connected to the Internet, so no gateway and no default route.

#+begin_example
DEVICE=p4p1
ONBOOT=yes
NETBOOT=yes
BOOTPROTO=static
TYPE=Ethernet
ONBOOT=yes
DEFROUTE=no
UUID="6b561b83-b86c-4412-b84a-fe2932ebb0c5"
HWADDR=00:e0:81:bb:b8:1a
IPADDR=10.0.0.202
NETMASK=225.225.225.0
ZONE=trusted
DOMAIN=kinto.dom
#+end_example

The second interface is connected directly to the Internet, so we make
this the default route include a gateway address and include it in the
public zone.

#+begin_src sh
emacs /etc/sysconfig/network-scripts/ifcg-p4p2
#+end_src

#+begin_example
NAME=p4p2
DEVICE=p4p2
TYPE=Ethernet
BOOTPROTO=static
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
UUID=7cf9d06b-e739-44f9-9cb8-882413462f51
ONBOOT=yes
HWADDR=00:e0:81:bb:b8:1b
IPADDR=103.56.174.11
NETMASK=225.225.225.0
GATEWAY=103.56.174.1
ZONE=public
#+end_example

Save files and restart network services.

On CentOS:

#+begin_src sh
systemctl restart network
#+end_src

Plug in ethernet cables and try to ping both 10.0.0.1 and something on
the internet to ensure that DNS is working and that both NICs are
configured properly.

You don't have to but I usually reboot the server at the point to
ensure the new hostname sticks and check that selinux and
networkmanager are disabled and the new network configuration works.

Now from a host on the Internet see if you can ping and ssh into the box.

** Add ssh key & disable password login

SEE: [[./rb-ssh-keys.org][rb-ssh-keys.org]]

** Configure firwalld


