#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Install New LAMP Server
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-lamp-server.org
:Created:   2017-09-06T12:04@Prek Leap (11.642600N-104.919210W)
:ID:        6b31c842-f952-4536-a3d3-398b7f6b93b8
:VER:       557946357.533612152
:GEO:       48P-491193-1287029-15
:BXID:      proj:WKE2-7607
:Type:      runbook
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

This file is for installing a LAMP server.


First install a new VM using the New-VM Runbook


Check you have a fully qualified hostname:

#+begin_src sh
hostname
hostname -f
#+end_src

Do an update and upgrade

#+begin_src sh
sudo apt-get update && sudo apt-get upgrade
#+end_src

* Apache

** 1. Install Apache2

#+begin_src sh
sudo apt-get install apache2
#+end_src

** 2. Edit the main Apache configuration file and turn off the =KeepAlive= setting:

File: */etc/apaches/apache2.conf*

#+begin_src sh
sudo emacs /etc/apache2/apache2.conf
#+end_src

#+begin_example
KeepAlive  Off
#+end_example

** 3. Open /etc/apache2/mods-available/mpm_prefork.conf

File: */etc/apache2/mods-available/mpm_prefork.conf*

#+begin_src sh
sudo emacs /etc/apache2/mods-available/mpm_prefork.conf
#+end_src

#+begin_example
# prefork MPM
# StartServers: number of server processes to start
# MinSpareServers: minimum number of server processes which are kept spare
# MaxSpareServers: maximum number of server processes which are kept spare
# MaxRequestWorkers: maximum number of server processes allowed to start
# MaxConnectionsPerChild: maximum number of requests a server process serves

<IfModule mpm_prefork_module>
        StartServers              4
        MinSpareServers           20
        MaxSpareServers           40
        MaxRequestWorkers         200
        MaxConnectionsPerChild    4500
</IfModule>
#+end_example

** 4. On Debian 8

On Debian 8, the event module is enabled by default. This should be
disabled, and the prefork module enabled:

#+begin_src sh
sudo a2dismod mpm_event
sudo a2enmod mpm_prefork
#+end_src

** 5. Restart Apache:

#+begin_src sh
sudo systemctl restart apache2
#+end_src

* Configure Virtual Hosts

** Create directories for websites and websites’ logs

There can be as many virtual hosts files as needed.

#+begin_src sh
sudo mkdir -p /var/www/html/example.com/public_html
sudo mkdir /var/www/html/example.com/logs
#+end_src

Shampoo, rinse, repeat for as many domains as needed.

** 2. Create an =example.com.conf= file in =/etc/apache2/sites-available=

#+begin_src sh
sudo emacs /etc/apache2/sites-available/example.com.conf
#+end_src

#+begin_example
<VirtualHost *:80>
     ServerAdmin webmaster@example.com
     ServerName example.com
     ServerAlias www.example.com
     DocumentRoot /var/www/html/example.com/public_html/
     ErrorLog /var/www/html/example.com/logs/error.log
     CustomLog /var/www/html/example.com/logs/access.log combined
</VirtualHost>
#+end_example

Shampoo, rinse, repeat for as many domains as needed.

** 3. Create symbolic link your from =sites-available= =sites-enabled= 

#+begin_src sh
sudo a2ensite example.com.conf
sudo a2ensite example.org.conf
#+end_src

To disable a site, use =a2dissite example.com=.

** 4. sudo systemctl restart apache2
