#   -*- mode: org; fill-column: 60 -*-

#+TITLE:  Basic PXE Server on Ubuntu Server
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-runbook-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Basic PXE Server on Ubuntu Server
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/deerpig/runbooks/rb-pxe-server.org
  :Created:   2018-07-18T10:50@Prek Leap (11.642600N-104.919210W)
  :ID:        81d60373-f1ef-470a-8ab6-0d683f1588a8
  :VER:       585157868.617256729
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:MTV4-2056
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

Install a basic PXE Server on Ubuntu Server LTS 16.04.

This server isn't needed that often.  Most provisioning of new
OpenStack compute nodes and such will be done using MAAS.  But there
will be times when you'll need to PXE boot stand alone boxes without
having to invoke lot's of infrastructure.  In our case, the Dell Cloud
Servers we use can't install from a usb drive, they have to boot from
the network.  So to build a MAAS server, which will provision and
instal conjure-up and juju which will install and set up an OpenStack
cluster we need to install Ubuntu on one server first.  This runbook
describes how to set up a simple PXE server to do that.

Eventually we will turn this into an ansible playbook, so that we can
set up a temporary PXE server when the need arises in the future.

** Install Ubuntu Server

Do a bog standard minimal install of ubuntu server from a usb.

Run apt update and upgrade:

#+begin_src sh
sudo apt-get -y update &&
sudo apt-get -y upgrade
#+end_src

#+begin_src sh
sudo apt-get install emacs24-nox
#+end_src

Copy ssh keys so you don't have to log on when accessing the box from
elsewhere.  If the server is on a public network, turn off password
authentication in /etc/ssh/config. Yada Yada.

** Install DHCP, TFTP and NFS

Install DHCP, TFTP and NFS:

#+begin_src sh
sudo apt-get install isc-dhcp-Server inetutils-inetd tftpd-hpa syslinux nfs-kernel-Server
#+end_src

** Configure DHCP Server

Edit the DHCP config file:

#+begin_src sh
sudo emacs /etc/default/dhcp3-server
#+end_src

Add or edit the network interface that will be used, which is eth0 or
the equiv.

#+begin_example bash
INTERFACES="eth0"
#+end_example

#+begin_src sh
sudo emacs /etc/dhcp/dhcpd.conf
#+end_src

Edit as follows:

#+begin_example
default-lease-time 600;
max-lease-time 7200;
subnet 192.168.1.0 netmask 255.255.255.0 {
range 192.168.1.21 192.168.1.240;
option subnet-mask 255.255.255.0;
option routers 192.168.1.20;
option broadcast-address 192.168.1.255;
filename "pxelinux.0";
next-Server 192.168.1.20;
}
#+end_example

Start DHCP Service:

#+begin_src sh
sudo /etc/init.d/isc-dhcp-server start
#+end_src

** Configure TFTP Server

TFTP is like ftp, but doesn't require authentication.  The server will
listen for PXE clients on the network.  When it sees a box doing a
network boot, it will send the network package that was chosen from
the boot menu.

First open:

#+begin_src sh
sudo emacs /etc/inetd.conf
#+end_src

Edit as follows:

#+begin_example
tftp dgram udp wait root /usr/sbin/in.tftpd /usr/sbin/in.tftpd -s /var/lib/tftpboot
#+end_example

Now open:

#+begin_src sh
sudo emacs /etc/default/tftpd-hpa
#+end_src

#+begin_example sh
TFTP_USERNAME="tftp"
TFTP_DIRECTORY="/var/lib/tftpboot"
TFTP_ADDRESS="[:0.0.0.0:]:69"
TFTP_OPTIONS="--secure"
RUN_DAEMON="yes"
OPTIONS="-l -s /var/lib/tftpboot"
#+end_example

Enable boot service for =inetd= to start on boot and start =tftpd=.

#+begin_src sh
sudo update-inetd --enable BOOT
sudo service tftpd-hpa start
#+end_src

Check status

#+begin_src sh
sudo netstat -lu
#+end_src

You should see something like the following:

#+begin_example
Proto Recv-Q Send-Q Local Address Foreign Address State
udp 0 0 *:tftp *:*
#+end_example

** Configure PXE boot files

Create files used by PXE that must be in the tftp root directory and
copy filed from syslinux in the "/usr/lib/syslinux" to
"/var/lib/tftpboot".

#+begin_src sh
sudo mkdir /var/lib/tftpboot
sudo mkdir /var/lib/tftpboot/pxelinux.cfg
sudo mkdir -p /var/lib/tftpboot/Ubuntu/14.04/amd64/
sudo cp /usr/lib/syslinux/vesamenu.c32 /var/lib/tftpboot/
sudo cp /usr/lib/syslinux/pxelinux.0 /var/lib/tftpboot/
#+end_src

Edit the PXE Server config file:

#+begin_src sh
sudo emacs /var/lib/tftpboot/pxelinux.cfg/default
#+end_src

As follows:

#+begin_example sh
DEFAULT vesamenu.c32
TIMEOUT 100
PROMPT 0
MENU INCLUDE pxelinux.cfg/PXE.conf
NOESCAPE 1
LABEL Try Ubuntu 14.04 Desktop
MENU LABEL Try Ubuntu 14.04 Desktop
kernel Ubuntu/vmlinuz
append boot=casper netboot=nfs nfsroot=192.168.1.20:/var/lib/tftpboot/Ubuntu/14.04/amd64
initrd=Ubuntu/initrd.lz quiet splash
ENDTEXT
LABEL Install Ubuntu 14.04 Desktop
MENU LABEL Install Ubuntu 14.04 Desktop
kernel Ubuntu/vmlinuz
append boot=casper automatic-ubiquity netboot=nfs nfsroot=192.168.1.20:/var/lib/tftpboot/Ubuntu/14.04/amd64
initrd=Ubuntu/initrd.lz quiet splash
ENDTEXT
#+end_example

Edit "pxe.conf":

#+begin_src sh
MENU TITLE PXE Server
NOESCAPE 1
ALLOWOPTIONS 1
PROMPT 0
MENU WIDTH 80
MENU ROWS 14
MENU TABMSGROW 24
MENU MARGIN 10
MENU COLOR border 30;44 #ffffffff #00000000 std
#+end_src

** Add Ubuntu Server 16.04 Images to PXE Server

Download the ISO file into the /mnt directory. Change the file name to
the latest image:

#+begin_src sh
sudo cd /mnt
sudo wget http://releases.ubuntu.com/16.04/ubuntu-16.04.3-server-amd64.iso
#+end_src

Mount the ISO file and copy all the files to the TFTP diretory:

#+begin_src sh
sudo mount -o loop /mnt/ubuntu-14.04.3-desktop-amd64.iso /media/
sudo cp -r /media/* /var/lib/tftpboot/Ubuntu/14.04/amd64/
sudo cp -r /media/.disk /var/lib/tftpboot/Ubuntu/14.04/amd64/
sudo cp /media/casper/initrd.lz /media/casper/vmlinuz /var/lib/tftpboot/Ubuntu/
#+end_src

** Configure NFS Server to Export ISO Contents



** Configure the Network Interface

Open the network =interfaces= file:

#+begin_src sh
sudo emacs /etc/network/interfaces
#+end_src

We need to set a static IP for the box.

And change eth0 to whatever bizzare interface naming scheme that the
box was installed with.


Edit as follows:

#+begin_example 
# The loopback network interface
auto lo
iface lo inet loopback
# The primary network interface
auto eth0
iface eth0 inet static
address 192.168.1.20
netmask 255.255.255.0
gateway 192.168.1.1
dns-nameservers 8.8.8.8
#+end_example

Restart the network

#+begin_src sh
sudo /etc/init.d/networking restart
#+end_src

Run =ifconfig= to check that the changes took effect.

** Network Boot

Now, connect the box you want to install on, and the PXE server to a
switch that is not running DHCP.

Reboot the box that will be installed and choose Network Boot from the
bios.

** References


