#   -*- mode: org; fill-column: 60 -*-

#+TITLE: SSH Keys
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-ssh-keys.org
:Created:   2017-09-08T15:53@Prek Leap (11.642600N-104.919210W)
:ID:        7bf4797d-06b4-4a0b-8be9-56e4c32ced21
:VER:       558132891.916941263
:GEO:       48P-491193-1287029-15
:BXID:      proj:LHC7-4013
:Type:      runbook
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


*  SSH Keys (Linux)

** 1.Create SSH key pair

#+begin_src sh
cd ~/
mkdir .ssh
cd ~/.ssh
ssh-keygen -b 4096
#+end_src

This will create a 4096-bit RSA (and SHA256) which should be
pretty solid for the forseeable future.

You will be prompted for a location to save the keys, and
for an optional passphrase.  The passphrase is a backup
security measure so that if your private key is stolen, the
attacker will need your passphrase to be able to use the
key.

Two files will be generated, =id_rsa= and =id_rsa.pub=.  

Now double check that all permissions on the .ssh directory
and keys are correct.

#+begin_src sh
chmod 700 ./.ssh
chmod 600 ./id_rsa
chmod 644 ./authorized_keys
#+end_src

*** Further Reading

The page on [[https://wiki.archlinux.org/index.php/SSH_keys][SSH Keys]] the Arch Linux Wiki is excellent,
in-depth and fully referenced.

- [[https://wiki.archlinux.org/index.php/SSH_keys][SSH Keys]] | Arch Linux Wiki
- [[https://www.howtoforge.com/linux-basics-how-to-install-ssh-keys-on-the-shell][Linux Basics: How To Create and Install SSH Keys on the Shell]]

** 2.  SSH Agent

In order to be able to login to the server without using the password
every time, use SSH Agent during that session.

#+begin_src sh
ssh-agent BASH
ssh-add
#+end_src


* SSH Keys (MacOS)

todo

* SSH Keys (Windows)

todo

* Send Key & Username to Kinto

Send a copy of the public key along with a preferred name
for the machine to whoever is setting up your VM at Chenla d9d.

When the VM is ready you will get back an ip address, machine name,
and possibly a domain name.
