#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Xmodmap Playbook
#+AUTHOR: Brad Collins
#+EMAIL: brad@chenla.la
#+STARTUP: showall
#+TOC: headlines 4
+PROPERTY: header-args    :results drawer  :tangle /home/deerpig/proj/playbooks/xmodmap.yml
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/deerpig/runbooks/rb-xmodmap.org
  :Created:   2019-05-18T12:36@Prek Leap (11.642600N-104.919210W)
  :ID:        24d9ad6d-79a0-475f-8fa1-9a6b15e413d8
  :VER:       611429825.450737463
  :GEO:       48P-491193-1287029-15
  :BXID:      pig:UWJ6-1625
  :Class:     dotemacs
  :Type:      literate-program
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-dotemacs-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-literate%20program-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

This file generates two ansible files:

The first =playbooks/pb-xmodmap.yml= is standalone playbook
that tangles =dot-xmodmap.org= which generates a .Xmodmap in
the home directory and then calls xmodmap to use the new
configuration.

The second is for use in the <workstation> role that
performs a full installation of Bunsen Labs on a laptop or
desktop.

** Notes

Written for Ansible: 2.7

  - git pull latest version of repo
  - org tangle the file dot-xodmap.org 

NOTE: restarting xmodmap using a handler command results in
an error.  I've removed the handler as it isn't terribly
important in a desktop environment.  When logging into the
machine, xmodmap will load .Xmodmap if it has changed.  So
the worst case scenario is to have to do this by hand.


* Playbooks
:PROPERTIES:
:ID:       c640f8af-f4e1-4461-bbdd-7b9b6a035bde
:END:

#+BEGIN_SRC yaml :session standalone :tangle /home/deerpig/proj/playbooks/pb-xmodmap.yml :noweb yes
---
- name: Configure xmodmap
  hosts: localhost
  become: true
  become_user: deerpig
  vars:
    home    : /home/deerpig
    rb_repo : /home/deerpig/proj/deerpig/runbooks
  tasks:
  <<plays>>


#+END_SRC

#+BEGIN_SRC sh :session tasks :tangle /home/deerpig/proj/playbooks/task-xmodmap.yml :noweb yes
---
# xmodmap tasks

<<plays>>
#+END_SRC

** Playbook
:PROPERTIES:
:header-args: :noweb-ref plays 
:END:
#+RESULTS:


#+begin_src yaml  :session standalone

    - name: git pull runbooks repo
      sudo: no
      git:
        repo: 'git@git.chenla.org:deerpig/runbooks.git'
        dest: /home/deerpig/proj/deerpig/dotfiles
        key_file: /home/deerpig/.ssh/d9d_admin
        accept_hostkey: true
        update: yes
        force: yes
        
    - name: tangle file
      command: emacs --batch -l org --eval '(org-babel-tangle-file "{{ rb_repo }}/dot-xmodmap.org")'
      args:
        removes: "{{ home }}/.Xmodmap"



#+end_src

** Workstation Role Tasks
:PROPERTIES:
:header-args: :noweb-ref plays
:END:

Now export as a task file for the <xxx> role

#+begin_src sh :session tasks

#+end_src

