#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Setting Up A VM on Kinto Cloud Service
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/deerpig-install/rb-new-vm-install.org
:Created:   2016-08-06T14:19@Wat Phnom (11.5733N17-104.925295W)
:ID:        6de8e89f-1bfb-44d1-8bd2-f68e1dc44109
:VER:       558131119.840072642
:GEO:       48P-491193-1287029-15
:BXID:      proj:TKW5-6453
:Type:      runbook
:Status:    stub
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/type-runbook-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

This document assumes that they are using a linux desktop
environment.  If you are using OSx or Windows some of this
will have to be adjusted for your OS.

We will assume that you have already generated and installed
a SSH key pair locally, and that a VM has been launched with
your ssh key.

This document will describe how to set up a clean VM.

* 1. First Login

SSH into the newly minted VM.

The VM was created using the public key sumbited, but no
user accounts are created, so a temporary account is created
that contains your public key for the first login.  Kinto
Cloud can not access your VM because that would require a
copy of your public key which is the only way to access the
VM.

The stock username depends on the VM's distro:

  - debian
  - ubuntu
  - centos

#+begin_src sh
ssh <distroname>@192.0.2.25
#+end_src

* 2. Update Software

Do a quick =yum= or =apt-get= update. 

Debian

#+begin_src sh
sudo apt-get update && sudo apt-get upgrade
#+end_src


* 3. Install Emacs

Since these are servers, there is no need to install full
blown versions of emacs which require you to install X and
other stuff which has no business being installed on any 
server, let alone a server in a public cloud server.

The address this, there are =nox= (as in no X11)
distributions of emacs which are small, light weight and
very fast, while still having all that lovely emacs
goodness.  They are designed to be plain-vanilla emacs, so
you won't have fanccy stuff like =Helm= installed, but
that's okay.  The only thing you should be doing on a server
is editing config files.

On =CentOS=:

#+begin_src sh
sudo yum install emacs-nox
#+end_src

On =Debian= & =Ubuntu=:

#+begin_src sh
sudo apt-get install emacs24-nox
#+end_src

* 4. Create new User

Create the =wheel= group which is still used by some
software packages.

#+begin_src sh
sudo groupadd wheel
#+end_src

Create the new user and include them in the =wheel= and
=sudo= groups.  You will be prompted to create a password.

#+begin_src sh
sudo adduser <username>
sudo usermod -a -G sudo,wheel <username>
#+end_src

* 5. Copy .ssh key directory to new user 

Copy the ssh key that is in the default user directory to
the new account.  Then change the ownership and group to the
new user.

#+begin_src sh
sudo cp -r .ssh /home/<username>/
sudo chown -R <username>:<username> /home/<username>/.ssh
#+end_src

Exit and ssh back into the machine as your new user.

* 6. Delete default user

If everything seems to be working (sudo something) then
delete the default user account and their home directory.

#+begin_src sh
sudo userdel -r <distroname>
#+end_src

* 7. Install some useful stuff

Use =apt-get= or =yum=, depending on the distro, to install
wget, curl, git-core, and lynx.

#+begin_src sh
sudo apt-get install wget curl git-core lynx
#+end_src

* 8. What's Next?

You should now have a base plain-vanilla server.  From here you can
[[./rb-lamp-server.org][install a LAMP stack]], or whatever your heart desires....

